//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zp8 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class GlobalCfg : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalCfg defaultInstance = ((GlobalCfg)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalCfg())));
        
        public static GlobalCfg Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string currentdb {
            get {
                return ((string)(this["currentdb"]));
            }
            set {
                this["currentdb"] = value;
            }
        }
    }
}
